### ISSUE TITLE
German variant

### ISSUE THREAD

**Issue by caco3** [pietroppeter/wordle-it#14]
Dear @pietroppeter 

I like the game and your clone of it :)
I decided to create a German variant of it.
I already reserved some domains [wordle-deutsch.ch](https://wordle-deutsch.ch) and [wordle-deutsch.de](https://wordle-deutsch.de) and pulled your repo to it. Of course I will keep all your copyright notes.

Now I have some questions:
1. I see the wordlist is in the variable `Aa` in `wordle-it.js`. But what is `Ta` for?
2. I see you also kept other wordlists in the repo (`60_000_parole.txt`, `itLines.js` and `dictionary.txt`), is there a reason for it?

**Comment by pietroppeter** [comment]
Hi @caco3, thanks for the kind words but let me point out a possible misunderstanding. The code here is not a clone of the original, it is a simple translation of the original. I downloaded the html and JS from the original website and made the minimal changes necessaries to make it into an Italian version. As such I have absolutely no copyright to this. I did try to reach out to the original author (both via tweet linked in readme and privately by email) but for the moment I have no response (he is very likely overwhelmed and this is likely not a priority or he has not noticed). Honestly I am not so sure I would advise you to use this, you would have to make your own considerations.

Regarding your other questions:

1. There are two lists of words: one is the list of words that will be used as the answer say by day. The second list is a list of additional words that can be used as guess (but will not be used as answer).

2. itLines.js is generated started from the two Italian dictionaries using the itLines.nim Nim code (Nim is a relatively unknown programming language). It is a very simple script (not particularly well written) that you could replicate in any language. I kept them in the repository because they are an essential step in building the final js

**Comment by caco3** [comment]
Dear @pietroppeter 

Thank you for your explanations.
It was a bit late in the night so I didn't realize you did it that ways. But I actually also the same idea for a moment.
I think I will handle it the same way as you.

So all it needs are the `Aa` and `Ta` list?

Most probably the hardest task is to get a clean, legal list of words.

**Comment by pietroppeter** [comment]
Yes all you need to start is those two list and yes the hardest thing I did was find the dictionaries. Original author from what I gather had a big dictionary and curated the list to select only this that will appear in the answer. I am using a small dictionary for answers and a bigger dictionary to add more words to use as guesses. I also play the day before tomorrow's word to make sure it is okay.

**Comment by pietroppeter** [comment]
An additional note. If you download now html and js from the original site you will find a recent change added a copyright reserved note (you see it at the bottom of settings screen). It was not there when I did the download (I think one of my earliest commit has the version I downloaded).

**Comment by caco3** [comment]
Yes, I see in https://www.powerlanguage.co.uk/wordle/main.c1506a22.js, but not in the html file.

Odly it is stated as copyrighted by Microsoft, which most likely is wrong.
But it gives full permissions to use it :)

**Comment by pietroppeter** [comment]
you might want also to remove the analytics tag: https://github.com/caco3/wordle-de/blob/f0776363b4d20743b10d6b16b4f1a8bbc082eb74/index.html#L27

**Comment by caco3** [comment]
Just for your info.

There are now several German speakers which went with the clone approach, but also removed the original copyright  :(
Like you I didn't want to go that way and instead found a close but nicely programmed Javascript alterative: https://github.com/soxfox42/typit
I already adapted it further (https://github.com/caco3/wordle-de) and will release it soon.
